# Generated by Django 5.2.5 on 2025-08-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_type', models.CharField(choices=[('collaborative', '协同过滤'), ('content_based', '基于内容'), ('hybrid', '混合推荐'), ('popularity', '热门推荐')], max_length=20, verbose_name='算法类型')),
                ('recommendation_score', models.FloatField(verbose_name='推荐分数')),
                ('recommendation_reason', models.TextField(blank=True, verbose_name='推荐原因')),
                ('is_clicked', models.BooleanField(default=False, verbose_name='是否点击')),
                ('is_bookmarked', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('user_rating', models.IntegerField(blank=True, null=True, verbose_name='用户评分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='点击时间')),
            ],
            options={
                'verbose_name': '推荐日志',
                'verbose_name_plural': '推荐日志',
                'db_table': 'recommendation_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, verbose_name='搜索词')),
                ('results_count', models.PositiveIntegerField(default=0, verbose_name='结果数量')),
                ('search_type', models.CharField(choices=[('general', '全文搜索'), ('title', '标题搜索'), ('tag', '标签搜索'), ('category', '分类搜索'), ('url', 'URL搜索')], default='general', max_length=20, verbose_name='搜索类型')),
                ('clicked_results', models.JSONField(default=list, verbose_name='点击结果')),
                ('search_duration', models.FloatField(default=0.0, verbose_name='搜索耗时')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '搜索日志',
                'verbose_name_plural': '搜索日志',
                'db_table': 'search_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('bookmark_add', '添加书签'), ('bookmark_delete', '删除书签'), ('bookmark_visit', '访问书签'), ('category_create', '创建分类'), ('category_update', '更新分类'), ('search', '搜索'), ('export', '导出数据'), ('import', '导入数据')], max_length=20, verbose_name='活动类型')),
                ('description', models.TextField(blank=True, verbose_name='活动描述')),
                ('metadata', models.JSONField(default=dict, verbose_name='元数据')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户活动',
                'verbose_name_plural': '用户活动',
                'db_table': 'user_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bookmarks', models.PositiveIntegerField(default=0, verbose_name='总书签数')),
                ('total_categories', models.PositiveIntegerField(default=0, verbose_name='总分类数')),
                ('total_tags', models.PositiveIntegerField(default=0, verbose_name='总标签数')),
                ('total_visits', models.PositiveIntegerField(default=0, verbose_name='总访问次数')),
                ('login_count', models.PositiveIntegerField(default=0, verbose_name='登录次数')),
                ('active_days', models.PositiveIntegerField(default=0, verbose_name='活跃天数')),
                ('avg_daily_visits', models.FloatField(default=0.0, verbose_name='日均访问')),
                ('activity_by_hour', models.JSONField(default=dict, verbose_name='按小时活动分布')),
                ('activity_by_day', models.JSONField(default=dict, verbose_name='按天活动分布')),
                ('activity_by_month', models.JSONField(default=dict, verbose_name='按月活动分布')),
                ('favorite_categories', models.JSONField(default=list, verbose_name='偏好分类')),
                ('favorite_tags', models.JSONField(default=list, verbose_name='偏好标签')),
                ('browsing_patterns', models.JSONField(default=dict, verbose_name='浏览模式')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '用户统计',
                'verbose_name_plural': '用户统计',
                'db_table': 'user_statistics',
            },
        ),
        migrations.CreateModel(
            name='WebsiteStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.PositiveIntegerField(default=0, verbose_name='总访问次数')),
                ('unique_visitors', models.PositiveIntegerField(default=0, verbose_name='独立访客数')),
                ('avg_visit_duration', models.FloatField(default=0.0, verbose_name='平均访问时长')),
                ('daily_visits', models.JSONField(default=dict, verbose_name='每日访问')),
                ('weekly_visits', models.JSONField(default=dict, verbose_name='每周访问')),
                ('monthly_visits', models.JSONField(default=dict, verbose_name='每月访问')),
                ('bookmark_count', models.PositiveIntegerField(default=0, verbose_name='收藏次数')),
                ('share_count', models.PositiveIntegerField(default=0, verbose_name='分享次数')),
                ('rating_avg', models.FloatField(default=0.0, verbose_name='平均评分')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='评分次数')),
                ('recommendation_score', models.FloatField(default=0.0, verbose_name='推荐分数')),
                ('similarity_scores', models.JSONField(default=dict, verbose_name='相似度分数')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '网站统计',
                'verbose_name_plural': '网站统计',
                'db_table': 'website_statistics',
            },
        ),
    ]
