# Generated by Django 5.2.5 on 2025-08-09 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('websites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationlog',
            name='recommended_website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to='websites.website', verbose_name='推荐网站'),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='websitestatistics',
            name='website',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='websites.website', verbose_name='网站'),
        ),
        migrations.AddIndex(
            model_name='recommendationlog',
            index=models.Index(fields=['user', 'created_at'], name='recommendat_user_id_38c571_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationlog',
            index=models.Index(fields=['algorithm_type'], name='recommendat_algorit_1fe914_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['user', 'created_at'], name='search_logs_user_id_f35125_idx'),
        ),
        migrations.AddIndex(
            model_name='searchlog',
            index=models.Index(fields=['query'], name='search_logs_query_5b6409_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'activity_type'], name='user_activi_user_id_290628_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'created_at'], name='user_activi_user_id_c742e0_idx'),
        ),
    ]
