# Generated by Django 5.2.5 on 2025-08-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('url', models.URLField(verbose_name='网址')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('notes', models.TextField(blank=True, verbose_name='笔记')),
                ('thumbnail', models.URLField(blank=True, verbose_name='缩略图')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='收藏')),
                ('is_archived', models.BooleanField(default=False, verbose_name='归档')),
                ('visit_count', models.PositiveIntegerField(default=0, verbose_name='访问次数')),
                ('last_visited', models.DateTimeField(blank=True, null=True, verbose_name='最后访问时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '书签',
                'verbose_name_plural': '书签',
                'db_table': 'bookmarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='收藏夹名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='颜色')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认收藏夹')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '收藏夹',
                'verbose_name_plural': '收藏夹',
                'db_table': 'collections',
                'ordering': ['-created_at'],
            },
        ),
    ]
